// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TZ_Infotecs_Winter_2026.Infrastructure.Data;

#nullable disable

namespace TZ_Infotecs_Winter_2026.Infrastructure.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TZ_Infotecs_Winter_2026.Domain.Entities.Result", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<double>("AverageExecutionTime")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_execution_time");

                    b.Property<double>("AverageValueDefinition")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_value");

                    b.Property<double>("MaxValueDefinition")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MedianValueDefinition")
                        .HasColumnType("double precision")
                        .HasColumnName("median_value_definition");

                    b.Property<double>("MinValueDefinition")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<DateTime>("MinimalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("minimal_date");

                    b.Property<double>("TimeDeltaSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("time_delta_seconds");

                    b.HasKey("FileName");

                    b.HasIndex("AverageExecutionTime")
                        .HasDatabaseName("idx_results_execution_time");

                    b.HasIndex("AverageValueDefinition")
                        .HasDatabaseName("idx_results_avg_value");

                    b.HasIndex("MinimalDate")
                        .HasDatabaseName("idx_results_min_date");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("TZ_Infotecs_Winter_2026.Domain.Entities.Value", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("value_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<double>("ValueDefinition")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("idx_values_date");

                    b.HasIndex("FileName")
                        .HasDatabaseName("idx_values_file_name");

                    b.ToTable("values", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
